# -*- coding: utf-8 -*-
"""Prepare_Input_CNN

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nYmzbeDHvOWmqn53pmAHkDtCSoyVmcKc
"""

from PIL import Image
from numpy import array
import  numpy
from keras.utils import np_utils
from skimage import io
import cv2

#load the datasets

# create list of  files name 
import glob, os
filesNames_CubeControl=[]
# images
os.chdir("/content/drive/MyDrive/pentagon_data_pic/without pressure/32×32/Augmentation/control")

for file in glob.glob("*.png"):
    filesNames_CubeControl.append(file)



# RGBA images
input_CNN=[]
output_CNN=[]

#collect control data and put it in the corect format for CNN input
#read B&W  images 
for imageName in filesNames_CubeControl:
    temp=[]
    img = cv2.imread(imageName,0)
    temp.append(img)
    arr=array(temp)
    input_CNN.append(arr)
    output_CNN.append([0])

#array(dataInput_CubeControl)
print (len(input_CNN))
print (len(output_CNN))




# create list of  files name 
import glob, os
filesNames_CubePatient=[]
os.chdir("/content/drive/MyDrive/pentagon_data_pic/without pressure/32×32/Augmentation/patient")

for file in glob.glob("*.png"):
    filesNames_CubePatient.append(file)


#appent patients fata to the control one
#read B&W 32x32 images 
for imageName2 in filesNames_CubePatient:
    temp2=[]
    img2 = cv2.imread(imageName2,0)
    temp2.append(img2)
    arr2=array(temp2)
    input_CNN.append(arr2)
    output_CNN.append([1])
    
#array(dataInput_CubeControl)
print (len(input_CNN))
print (len(output_CNN))



from tempfile import TemporaryFile
outfile = TemporaryFile()
numpy.save("/content/drive/MyDrive/pentagon_data_pic/without pressure/32×32/Augmentation/input_CNN_cube", input_CNN)
numpy.save("/content/drive/MyDrive/pentagon_data_pic/without pressure/32×32/Augmentation/output_CNN_cube", output_CNN)